projet/application/urls.py
from django.urls import path
from . import views
from .views import HomeView

app_name = 'application'
urlpatterns = [
    path("index/", views.index, name='index'),
    path('', HomeView.as_view(), name='home'),
    path('ajout/', views.ajout, name='ajout'),
    path("traitement/", views.traitement),
    path("affiche/<int:id>/", views.affiche),
    path("delete/<int:id>", views.delete),
    path("update/<int:id>", views.update),
    path("updatetraitment/<int:id>", views.updatetraitment),
    path("ajoutc/", views.ajoutc, name="ajoutc"),
    path("traitementc/", views.traitementc),
    path("updatec/<int:id>", views.updatec),
    path("traitementupdatec/<int:id>", views.traitementupdatec),
    path("affichec/<int:id>", views.affichec),
    path("deletec/<int:id>", views.deletec),
]

projet/projet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('application/', include('application.urls')),
    path('', include('application.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projet/application/models.py
from django.db import models

# Create your models here.


class Avion(models.Model):
    nom = models.CharField(max_length=100)
    constructeur = models.CharField(max_length=100)
    date_production = models.DateField(blank=True, null=True)
    nombre_appareils = models.IntegerField(blank=False)
    presentation = models.TextField(null=True, blank=True)
    categorie = models.ForeignKey("categorie", on_delete=models.CASCADE, default=None)

    def __str__(self):
        chaine = f"{self.nom} de {self.constructeur} créé en {self.date_production}"
        return chaine

    def dico(self):
        return {"nom" : self.nom, "constructeur" : self.constructeur, "date_production" : self.date_production, "nombre_appareils" : self.nombre_appareils, "presentation" : self.presentation, "categorie" : self.categorie}


class Categorie(models.Model):
    usage = models.CharField(max_length=100)
    nomc = models.CharField(max_length=100)

    def __str__(self):
        chaine = f"{self.nomc} est à usage {self.usage}"
        return chaine

    def dico(self):
        return {"nom" : self.nomc, "usage" : self.usage}

projet/application/forms.py
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _
from . import models


class AvionForm(ModelForm):
    class Meta:
        model = models.Avion
        fields = {'nom', 'constructeur', 'date_production', 'nombre_appareils', 'presentation', 'categorie'}
        labels = {
            'nom': _('Nom'),
            'constructeur': _('Constructeur'),
            'date_production': _('Date de production'),
            'nombre_appareils': _('Nombre appareils'),
            'presentation': _('Présentation'),
            'categorie': _('Catégorie'),
        }


class CategorieForm(ModelForm):
    class Meta:
        model = models.Categorie
        fields = {'nomc', 'usage'}
        labels = {
            'nomc': _('Nom de la catégorie'),
            'usage': _('Usage de la catégorie'),
        }

projet/application/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .forms import AvionForm
from . import models
from django.http import HttpResponseRedirect
from .forms import AvionForm
from .forms import CategorieForm


# Create your views here.


class HomeView(TemplateView):
    template_name = 'main.html'


def ajout(request):
    if request.GET.get("POST"):
        form = AvionForm(request)
        if form.is_valid():
            livre = form.save()
            return HttpResponseRedirect("/application/")
        else:
            return render(request,"application/ajout.html",{"form": form})
    else :
        form = AvionForm()
        return render(request,"application/ajout.html",{"form" : form})


def traitement(request):
    lform = AvionForm(request.POST)
    if lform.is_valid():
        avion = lform.save()
        return HttpResponseRedirect("/application/index")
    else:
        return render(request,"application/ajout.html",{"form": lform})


def index(request):
    liste = list(models.Avion.objects.all())
    return render(request, 'application/index.html', {'liste': liste})


def affiche(request, id):
    avion = models.Avion.objects.get(pk=id)
    return render(request,"application/affiche.html",{"avion" : avion})


def delete(request, id):
    avion = models.Avion.objects.get(pk=id)
    avion.delete()
    return HttpResponseRedirect("/application/index/")


def update(request, id):
    avion = models.Avion.objects.get(pk=id)
    lform = AvionForm(avion.dico())
    return render(request, "application/update.html", {"form": lform, "id": id})


def updatetraitment(request, id):
    lform = AvionForm(request.POST)
    if lform.is_valid():
        avion = lform.save(commit=False)
        avion.id = id
        avion.save()
        return HttpResponseRedirect("/application/index/")
    else:
        return render(request, "application/update.html", {"form": lform, "id": id})


################################################################

def affichec(request, id):
    categorie = models.Categorie.objects.get(pk=id)
    return render(request,"application/affichec.html",{"categorie" : categorie})


def ajoutc(request):
    listec = list(models.Categorie.objects.all())
    if request.GET.get("POST"):
        form = CategorieForm(request)
        if form.is_valid():
            livre = form.save()
            return HttpResponseRedirect("/application/")
        else:
            return render(request,"application/ajoutc.html",{"form": form, 'listec': listec})
    else :
        form = CategorieForm()
        return render(request,"application/ajoutc.html",{"form": form, 'listec': listec})


def traitementc(request):
    lform = CategorieForm(request.POST)
    if lform.is_valid():
        avion = lform.save()
        return HttpResponseRedirect("/application/index/")
    else:
        return render(request,"application/ajoutc.html",{"form": lform})


def deletec(request, id):
    avion = models.Categorie.objects.get(pk=id)
    avion.delete()
    return HttpResponseRedirect("/application/index/")


def updatec(request, id):
    categorie = models.Categorie.objects.get(pk=id)
    cform = CategorieForm(categorie.dico())
    return render(request, "application/updatec.html", {"form": cform, "id": id})


def traitementupdatec(request, id):
    lform = CategorieForm(request.POST)
    if lform.is_valid():
        categorie = lform.save(commit=False)
        categorie.id = id
        categorie.save()
        return HttpResponseRedirect("/application/index")
    else:
        return render(request, "application/updatec.html", {"form": lform, "id": id})

projet/application/templates/affiche.html
{% extends 'main.html' %}

{% block content %}

<p>Vous avez ajouté l'avion suivant : {{avion}} {{avion.id}}</p>

{% endblock %}

projet/application/templates/application/affiche.html
{% extends 'main.html' %}

{% block content %}

<p class="titreaffiche">Details sur l'avion : {{avion.nom}}</p>

<p class="presentationaffiche">Fiche technique brève de l'avion : {{avion.nom}}</p>

<table class="tg">
<thead>
  <tr>
    <th class="tg-0lax">Catégorie</th>
    <th class="tg-0lax">Valeur</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-0lax">Catégorie</td>
    <td class="tg-0lax">{{avion.categorie}}</td>
  </tr>
  <tr>
    <td class="tg-0lax">Date de production</td>
    <td class="tg-0lax">{{avion.date_production}}</td>
  </tr>
  <tr>
    <td class="tg-0lax">Nombre d'appareils</td>
    <td class="tg-0lax">{{avion.nombre_appareils}}</td>
  </tr>
</tbody>
</table>

<p class="presentationaffiche">Présentation de l'avion : {{avion.nom}}</p>

<p class="presentationaffiche">{{avion.presentation}}</p>

{% endblock %}

projet/application/templates/application/affichec.html
{% extends 'main.html' %}

{% block content %}

<p class="titreaffiche">Details sur l'avion : {{categorie.nomc}}</p>

<p class="presentationaffiche">{{categorie.nomc}} et {{categorie.usage}}</p>

{% endblock %}

projet/application/templates/application/ajout.html
{% extends "application/main.html" %}

{% block content %}
<form class="form-horizontal" method="post" action="/application/traitement/">
{% csrf_token %}
<fieldset>
<legend>Ajout d'un avion</legend>
  <ul>
    {{form.as_ul}}
  </ul>
  <input type="submit" value="envoyer les données"/>
</fieldset>
</form>
{% endblock %}

projet/application/templates/application/ajoutc.html
{% extends "application/main.html" %}

{% block content %}
<form class="form-horizontal" method="post" action="/application/traitementc/">
{% csrf_token %}
<fieldset>
<legend>Ajout d'une catégorie</legend>
  <ul>
    {{form.as_ul}}
  </ul>
  <input type="submit" value="envoyer les données"/>
</fieldset>
</form>

<p class="presentationaffiche">Catégories déjà présente : </p>

<ol>
    {% for l in listec %}
        <li> {{l}} <a href="/application/affichec/{{l.id}}"> | Détails </a><a href="/application/updatec/{{l.id}}"> | Update </a><a href="/application/deletec/{{l.id}}"> | Delete</a></li>
    {% endfor %}
</ol>

{% endblock %}

projet/application/templates/application/index.html
{% extends 'main.html' %}

{% block content %}

<div class="textepresentation">
<p>Bienvenue sur le site web "Wikiplane".</p>
<p>Vous retrouverez un catalogue d'avion ainsi qu'une page d'ajout, de modification et de supression</p>
<p>Bonne visite !</p>

<hr class="rounded">

<p>Utilisez la barre de navigation pour accéder aux différentes pages</p>

<hr class="rounded">

<p>Catalogue du site : </p>

</div>

<ol>
    {% for l in liste %}
        <li> {{l}} <a href="/application/affiche/{{l.id}}"> | Détails </a><a href="/application/update/{{l.id}}"> | Update </a><a href="/application/delete/{{l.id}}"> | Delete</a></li>
    {% endfor %}
</ol>

{% endblock %}

projet/application/templates/application/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@340&display=swap" rel="stylesheet">
    <title>Wikiplane</title>
</head>
<body>

    <div class="header">
            <img class="photorafale" src="{% static 'images/rafale.jpg' %}" alt="Photo Rafale NG">
            <h1 id="top1">Wikiplane</h1>
            <h3 id="top2">Votre catalogue web de l'aviation</h3>
    </div>

    <ul class="navbar">
        <li class="liens"><a href="{% url 'application:index' %}">Home</a></li>
        <li class="liens"><a href="{% url 'application:ajout' %}">Ajout d'un avion</a></li>
        <li class="liens"><a href="{% url 'application:ajoutc' %}">Ajout d'une catégorie</a></li>
    </ul>

    {% block content %}

    {% endblock %}

    <footer class="footer">
        Site web fait par Louis PLUVIOSE - RT13 | Django / HTML5 / CSS3 / JS
    </footer>
</body>
</html>

projet/application/templates/application/pagedelete.html
{% extends 'main.html' %}

{% block content %}

<div class="textepresentation">
<p>Comment accéder à la page de supression ?</p>
<p>Entrez l'url : /application/delete/*ID du post*</p>
<p>Vous pouvez trouver l'ID des posts sur le catalogue, présent sur la page d'acceuille</p>
</div>

{% endblock %}

projet/application/templates/application/pageedit.html
{% extends 'main.html' %}

{% block content %}

<div class="textepresentation">
<p>Comment accéder à la page d'édition ?</p>
<p>Entrez l'url : /application/update/*ID du post*</p>
<p>Vous pouvez trouver l'ID des posts sur le catalogue, présent sur la page d'acceuille</p>
</div>

{% endblock %}

projet/application/templates/application/pageupdate.html
{% extends 'main.html' %}

{% block content %}

<div class="textepresentation">
<p>Entrez sur le formulaire suivant l'id du poste que vous souhaitez éditer</p>
</div>

<form method="post" action="/application/update/id_id">
{% csrf_token %}
  <fieldset>
    <legend>Edition</legend>
    <label for="id_id">Id : <input type="number" name="id" required id="id_id"></label>
    <input type="submit" value="Envoyer les données">
  </fieldset>
</form>

{% endblock %}

projet/application/templates/application/tmp.html
{% extends "application/main.html" %}

{% block content %}
<form class="form-horizontal" method="post" action="/application/traitement/">
{% csrf_token %}
<fieldset>

<!-- Form Name -->
<legend>TMP</legend>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="id_nom">Nom</label>
  <div class="col-md-4">
  <input id="id_nom" name="nom" type="text" placeholder="Rafale" class="form-control input-md" required="" maxlength="100">
  <span class="help-block">Nom de l'avion à ajouter</span>
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="id_fabriquant">Fabriquant</label>
  <div class="col-md-4">
  <input id="id_fabriquant" name="fabriquant" type="text" placeholder="Dassault Aviation" class="form-control input-md" required="" maxlength="100">
  <span class="help-block">Nom du fabriquant de l'avion</span>
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="id_date_de_production">Date de production</label>
  <div class="col-md-4">
  <input id="id_date_de_production" name="date_de_production" type="date" placeholder="01/01/2010" class="form-control input-md">
  <span class="help-block">Date du début de la production de l'avion</span>
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="id_nombre_avion">Nombre d'avion</label>
  <div class="col-md-4">
  <input id="id_nombre_avion" name="nombre_avion" type="number" placeholder="350" class="form-control input-md" maxlength="100">
  <span class="help-block">Nombre d'avions produits</span>
  </div>
</div>

  <!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="id_categorie">Catégorie</label>
  <div class="col-md-4">
    <select id="id_categorie" name="categorie" class="form-control input-md"></select>
  </div>
</div>

<!-- Textarea -->
<div class="form-group">
  <label class="col-md-4 control-label" for="id_resume">Présentation</label>
  <div class="col-md-4">
    <textarea class="form-control" id="id_resume" name="resume"></textarea>
  </div>
</div>

<input type="submit" value="envoyer les données"/>

</fieldset>
</form>
{% endblock %}

projet/application/templates/application/update.html
{% extends 'main.html' %}

{% block content %}
  <form method="post" action="/application/updatetraitment/{{id}}">
  {% csrf_token %}
  <fieldset>
  <legend>Modification de l'avion {{avion.nom}}</legend>
    <ul>
      {{form.as_ul}}
    </ul>
    <input type="submit" value="envoyer les données"/>
  </fieldset>
  </form>

{% endblock %}

projet/application/templates/application/updatec.html
{% extends 'main.html' %}

{% block content %}

<form method="post" action="/application/traitementupdatec/{{id}}">
  {% csrf_token %}
  <fieldset>
  <legend>Modification de la catégorie {{categorie.nomc}}</legend>
    <ul>
      {{form.as_ul}}
    </ul>
    <input type="submit" value="envoyer les données"/>
  </fieldset>
</form>

{% endblock %}

projet/application/templates/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'images/airplane.ico' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@340&display=swap" rel="stylesheet">
    <title>Wikiplane</title>
</head>
<body>

    <div class="header">
            <img class="photorafale" src="{% static 'images/rafale.jpg' %}" alt="Photo Rafale NG">
            <h1 class="text">Wikiplane</h1>
            <h3 class="text">Votre catalogue web de l'aviation</h3>
    </div>

    <ul class="navbar">
        <li class="liens"><a href="{% url 'application:index' %}">Home</a></li>
        <li class="liens"><a href="{% url 'application:ajout' %}">Ajout</a></li>
        <li class="liens"><a href="{% url 'application:ajoutc' %}">Ajout d'une catégorie</a></li>
    </ul>

    {% block content %}

    {% endblock %}

    <footer class="footer">
        Site web fait par Louis PLUVIOSE - RT13 | Django / HTML5 / CSS3
    </footer>
</body>
</html>

projet/application/templates/update.html
{% extends 'main.html' %}

{% block content %}

<form method="post" action="/application/traitementupdate/{{avion.id}}">
    {% csrf_token %}
    {{ form.as_ul }}
<input type="submit" value="envoyer␣les␣données"\>
</form>

{% endblock %}